import React from "react";
import Form from "../../../forms/components/Form";
import Input from "../../../forms/components/Input";
import ROUTES from "../../../routes/routesModel";

export default function CreateCardForm({
    onSubmit,
    onReset,
    disabled,
    error,
    handleChange,
    data,
}) {
    return (
        <>
            <Form
                onSubmit={onSubmit}
                onReset={onReset}
                disabled={disabled}
                title="Create a New Card"
                styles={{ maxWidth: "800px" }}
                to={ROUTES.MY_CARDS}
                color="inherit"
                spacing={1}
            >
                <Input
                    name="title"
                    label="Title"
                    error={error.title}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                />
                <Input
                    name="subtitle"
                    label="Subtitle"
                    error={error.subtitle}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                />
                <Input
                    name="description"
                    label="Description"
                    error={error.description}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                />
                <Input
                    name="phone"
                    label="Phone"
                    type="phone"
                    error={error.phone}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                />
                <Input
                    name="email"
                    label="Email"
                    type="email"
                    error={error.email}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                />
                <Input
                    name="webUrl"
                    label="Web"
                    type="web"
                    error={error.web}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                    required={false}
                />
                <Input
                    name="imageUrl"
                    label="Image URL"
                    error={error.url}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                />
                <Input
                    name="imageAlt"
                    label="Image Alt"
                    error={error.alt}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                />
                <Input
                    name="state"
                    label="State"
                    error={error.state}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                    required={false}
                />
                <Input
                    name="country"
                    label="Country"
                    error={error.country}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                />
                <Input
                    name="city"
                    label="City"
                    error={error.city}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                />
                <Input
                    name="street"
                    label="Street"
                    error={error.street}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                />
                <Input
                    name="houseNumber"
                    label="House Number"
                    type="number"
                    error={error.houseNumber}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                />
                <Input
                    name="zip"
                    label="Zip"
                    error={error.zip}
                    handleChange={handleChange}
                    data={data}
                    sm={6}
                    required={false}
                />
            </Form>
        </>
    );
}
